"""Add website credentials to subscription model

Revision ID: 603e6e46243b
Revises: 1b6cb0d18c96
Create Date: 2025-04-07 06:56:01.595405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603e6e46243b'
down_revision = '1b6cb0d18c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website_password', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paused_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('remaining_days', sa.Integer(), nullable=True))
        batch_op.alter_column('subscription_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('subscription_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('remaining_days')
        batch_op.drop_column('paused_at')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('website_password')
        batch_op.drop_column('website_username')

    # ### end Alembic commands ###
