"""Add user_id to subscriptions table

Revision ID: 6072176daf3e
Revises: 7494a35d7037
Create Date: 2025-04-07 06:33:41.584370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6072176daf3e'
down_revision = '7494a35d7037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('website_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('subscription_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('subscription_term', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('start_date')
        batch_op.drop_column('term_months')
        batch_op.drop_column('grace_period_days')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('grace_period_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('term_months', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('payment_method')
        batch_op.drop_column('subscription_term')
        batch_op.drop_column('subscription_price')
        batch_op.drop_column('website_url')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('restaurant_name')

    # ### end Alembic commands ###
